---
- name: installing docker engine
  hosts: dockerm
  become: yes
  tasks:
    - name: updating cache
      apt:
        update_cache: yes
    - name: Install packages to allow apt to use a repository over HTTPS
      package:
        name: "{{item}}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Add Docker’s official GPG key
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        state: present
    - name: set up the stable repository.
      shell: sudo add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable" >> replog.txt
      args:
        creates: replog.txt
    - name: install  docker-ce docker-ce-cli containerd.io
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: check {command}
      command: docker version
      register: version
    - debug:
        var: version
